[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ednabp"
version = "0.0.1"
authors = [
  { name="Shan-En Chen", email="shawn.for.office@gmail.com" },
  { name="Steven Wu", email="stevenwu@ntu.edu.tw" },
]
description = "Analysis metagenomic data from the ocean"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dynamic = ["dependencies"]
[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[project.scripts]
eDNAbp = "fastq_processor_cli.cli:main"

[project.urls]
"Homepage" = "https://github.com/ComputationalAgronomy/ednabp.git"
"Bug Tracker" = "https://github.com/ComputationalAgronomy/ednabp.git" 

[tool.setuptools.packages.find]
where = ["src"]  # ["."] by default
include = ["*"]  # ["*"] by defaultgit 
## cause it trigger error, i disable it before i fixed it.
## Getting requirements to build editable ... error ...
# addopts = [
#     "--import-mode=importlib",
# ]

[flake8]
per-file-ignores = "tests/*: E501"  # E501 line too long

[tool.ruff]
line-length = 79
target-version = "py311"
extend-include = ["*.ipynb"]

[tool.ruff.lint]
select = [
  "E",  # pycodestyle errors
  "W",  # pycodestyle warnings
  "F",  # pyflakes
  "I",  # isort
  "B",  # flake8-bugbear
  "C4", # flake8-comprehensions
  "UP", # pyupgrade
  # "ARG001", # unused arguments in functions
]
ignore = [
  "E402", # module level import not at top of file
  "E501", # line too long, handled by black
  "B008", # do not perform function calls in argument defaults
  "W191", # indentation contains tabs
  "B904", # Allow raising exceptions without from e, for HTTPException
]

[tool.ruff.format]
quote-style = "double"