from ..common import base_logger

SETTINGS = {
    "enabled_stages": [
        "decompress",
        "merge",
        "cutprimer",
        "fqtofa",
        "dereplicate",
        "denoise",
        "blast",
        "addlineage",
        "addhap",
    ],
    "dir_name": {
        "decompress": "decompress",
        "merge": "merge",
        "cutprimer": "cutprimer",
        "fqtofa": "fqtofa",
        "dereplicate": "dereplicate",
        "denoise": "denoise",
        "blast": "blast",
        "addlineage": "blast",
        "addhap": "blast",
    },
    "suffix": {
        "raw": "AUTO",
        "decompress": "_R1.fastq",
        "merge": ".fastq",
        "cutprimer": ".fastq",
        "fqtofa": ".fasta",
        "dereplicate": ".fasta",
        "denoise": ".fasta",
        "blast": ".csv",
        "addlineage": ".csv",
        "addhap": ".csv",
        "report": "_report.txt",
        "denoise_report": "_denoise_report.txt",
    },
    "merge": {
        "maxdiff": 5,
        "pctid": 90,
    },
    "cutprimer": {
        "rm_p_5": "GTCGGTAAAACTCGTGCCAGC",
        "rm_p_3": "CAAACTGGGATTAGATACCCCACTATG",
        "error_rate": 0.15,
        "min_read_len": 163,
        "max_read_len": 185,
    },
    "denoise": {
        "minsize": 8,
        "alpha": 2,
    },
    "blast": {
        "evalue": 0.00001,
        "qcov_hsp_perc": 90,
        "perc_identity": 90,
        "specifiers": "qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore",
        "blast_db": "nt",
    },
    "addlineage": {
        "lineage_db": "nucleotide",
        "entrez_email": None,
    },
    "prog": {
        "usearch": "usearch",
        "cutadapt": "cutadapt",
        "blast": "blastn",
    },
    "config_basic": {
        "logger": base_logger.logger,
        "verbose": False,
        "dry": False,
    },
    "config_machine": {
        "n_cpu": 1,
        "memory": 8,
    },
}
